import Header from '@/components/Layout/Header/Header'
import Navigation from '@/components/Layout/Navigation/Navigation'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>BulletPoint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      <p>hello next</p>
      <p>hello next</p>
      <p>hello next</p>
      <p>hello next</p>
    </>
  )
}
